public class PlayersData {
    public static final String[][] PLAYERS={

            {"Yoichi Isagi","11","Atacante"},
            {"Meguru Bachira","8","Ponta"},
            {"Rensuke Kunigami","9","Atacante"},
            {"Hyoma Chigiri","7","Ponta"},
            {"Seishiro Nagi","10","Atacante"},
            {"Reo Mikage","14","Meio-campo"},
            {"Rin Itoshi","10","Atacante"},
            {"Sae Itoshi","10","Meio-campo"},
            {"Ryusei Shidou","13","Atacante"},
            {"Eita Otoya","17","Ponta"},
            {"Tabito Karasu","6","Volante"},
            {"Aoshi Tokimitsu","5","Volante"},
            {"Jyubei Aryu","4","Zagueiro"},
            {"Ikki Niko","3","Zagueiro"},
            {"Gin Gagamaru","1","Goleiro"},
            {"Oliver Aiku","4","Zagueiro"},
            {"Yo Hiori","16","Meio-campo"},
            {"Ranze Kurona","2","Lateral"},
            {"Zantetsu Tsurugi","7","Ponta"},
            {"Asahi Naruhaya","18","Atacante"},
            {"Wataru Kuon","15","Zagueiro"},
            {"Jingo Raichi","6","Volante"},
            {"Gurimu Igarashi","19","Atacante"},
            {"Kenyu Yukimiya","11","Ponta"},
            {"Michael Kaiser","10","Atacante"},
            {"Alexis Ness","8","Meio-campo"},
            {"Don Lorenzo","5","Zagueiro"},
            {"Julian Loki","7","Atacante"},
            {"Adam Blake","9","Atacante"},
            {"Lavinho","11","Ponta"},

            {"Son Goku","9","Atacante"},
            {"Naruto Uzumaki","7","Ponta"},
            {"Monkey D. Luffy","9","Atacante"},
            {"Batman","4","Zagueiro"},
            {"Spider-Man","11","Ponta"},
            {"Kratos","5","Zagueiro"},
            {"Geralt of Rivia","6","Volante"},
            {"Link","2","Lateral"},
            {"Mario","8","Meio-campo"},
            {"Sonic","7","Ponta"},
            {"Gon Freecss","9","Atacante"},
            {"Killua Zoldyck","7","Ponta"},
            {"Kurapika","10","Meio-campo"},
            {"Leorio Paradinight","8","Meio-campo"},
            {"Hisoka","11","Atacante"},
            {"Chrollo Lucilfer","6","Volante"},
            {"Illumi Zoldyck","4","Zagueiro"},
            {"Feitan","7","Ponta"},
            {"Uvogin","5","Zagueiro"},
            {"Kite","3","Lateral"}

    };
}
